name: Build Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  sast_pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies (Flask, SQLAlchemy, JWT, bcrypt, CORS, pytest)
      run: |
        pip install Flask flask_jwt_extended SQLAlchemy bcrypt flask_cors bandit pytest

    # Step 1: Run Bandit Security Check (excluding test files)
    - name: Run Bandit Security Check
      run: bandit -r user_service.py -x user_service_tests.py

    # Step 2: Run Unit Tests
    - name: Run Unit Tests
      run: pytest

    # Step 3: Run SonarCloud Scan
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      with:
        args: >
          -Dsonar.projectKey=nfmh_user-service
          -Dsonar.organization=nfmh
          -Dsonar.python.version=3.x
