name: Build Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  sast_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies (Flask, SQLAlchemy, JWT, bcrypt, CORS)
      run: |
        pip install Flask flask_jwt_extended SQLAlchemy bcrypt flask_cors bandit

    # Step 1: Run Bandit
    - name: Run Bandit Security Check
      run: bandit -r user-service/

    # Step 2: Run SonarCloud Scan
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.7
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      with:
        args: >
          -Dsonar.projectKey=nfmh_user-service
          -Dsonar.organization=nfmh
          -Dsonar.python.version=3.x
